---
- name: Run FRR route-server
  community.docker.docker_container:
    name: "{{ frr_rs_name }}"
    image: "{{ frr_image }}"
    state: started
    restart_policy: always
    capabilities: ["NET_ADMIN"]
    sysctls:
      net.ipv4.ip_forward: "1"
    networks:
      - name: "{{ ixp_net_name }}"
        ipv4_address: "{{ frr_rs_ip }}"
    volumes:
      - "{{ playbook_dir }}/../../services/frr/route-server/frr.conf:/etc/frr/frr.conf:ro"
